name: Keep Render Alive

on:
  schedule:
    # 06:00 - 11:59 WIB (Mon-Fri) is 23:00 - 04:59 UTC (Sun-Thu & Mon-Fri)
    # The first cron handles 23:00 to 23:59 UTC (which is 06:00-06:59 WIB Mon-Fri)
    - cron: '*/10 23 * * 0-4'
    # The second cron handles 00:00 to 04:59 UTC (which is 07:00-11:59 WIB Mon-Fri)
    - cron: '*/10 0-4 * * 1-5'
    
    # 16:00 - 19:59 WIB (Mon-Fri) is 09:00 - 12:59 UTC
    - cron: '*/10 9-12 * * 1-5'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: |
          curl -f -s ${{ secrets.RENDER_URL }}/ping || echo "Failed to ping, but continuing"
